### ISSUE TITLE
Remove link formatting after space. 

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#87] opened 2017-08-07 10:15 UTC
When i apply any styling to a word or a set of words i notice that the style does not remain if i continue writing after the styled words, and this is the expected behavior. 

What i don't expect is that the link styling remains when i continue to write, ideally after a space the style should be gone as in this [editor](https://yabwe.github.io/medium-editor/) or any other text editor.  

The steps to reproduce this issue are:
- write a sentence 
- link the complete sentence to an url 
- move the cursor to the last word of the sentence, and press `space`
- write something 

Eventually you will see that all the test is linked to the url, ideally text written after pressing `space` should be excluded from that.

**Comment by brijeshb42** [comment] 2017-08-27 11:38
Duplicate of #37

**Closed by brijeshb42** 2017-08-27 11:38 UTC
